package es.sms.bolsa.enumEntity;

import com.google.common.collect.ImmutableList;

public enum TipoMeritosItemEnum {
	
	TITULACION_EXPEDIENTE,MASTER,FORMACION_CONTINUADA,INVESTIGACION,INTERNO_RESIDENTE,TITULACION_PREMIO,
		FORMACION_ESPECIALIZADA,RELACION_FIJEZA,TITULACION,EXPRO_NO_OFICIO,TITULACION_DOCTORADO;

	
	

}
